USE Liverpool
GO

SELECT FACT.id, 
	   FACT.FECHA,
	   FACT.EMPLEADO,
	   FACT.ESTADO,
	   SUM( (IT.COSTO * IT.CANTIDAD) ) AS SUBTOTAL,
	   SUM( (IT.COSTO * IT.CANTIDAD) * 0.16 ) AS IVA
	FROM FACTURA AS FACT 
						INNER JOIN ITEM AS IT
						ON FACT.id = it.idFACTURA
	WHERE YEAR( FACT.FECHA ) = 2018 AND MONTH( FACT.FECHA ) = 2

	GROUP BY FACT.id, FACT.FECHA, FACT.EMPLEADO, FACT.ESTADO
GO
	/*Cuenta los articulos y los agrupa por id*/
SELECT IT.idARTICULO, COUNT( IT.idARTICULO ) AS CANTIDAD_ARTICULOS
		FROM FACTURA AS FACT 
			INNER JOIN ITEM AS IT
			ON FACT.id = idFACTURA
		GROUP BY IT.idARTICULO
		ORDER BY IT.idARTICULO DESC

GO

/*Selecciona nombre, Cuenta los articulos y los agrupa por id*/
SELECT IT.idARTICULO, COUNT( IT.idARTICULO ) AS CANTIDAD_ARTICULOS,
(SELECT ARTICULO.NOMBRE FROM ARTICULO WHERE ARTICULO.id = IT.idARTICULO) AS NOMBRE_ARTICULO
		FROM FACTURA AS FACT 
			INNER JOIN ITEM AS IT
			ON FACT.id = idFACTURA
		GROUP BY IT.idARTICULO
		ORDER BY IT.idARTICULO DESC
GO

/*Selecciona nombre, Cuenta los articulos y los agrupa por id (Articulo mas vendido EN CANTIDAD)*/
SELECT TOP 1 IT.idARTICULO AS ID, COUNT( IT.idARTICULO ) AS CANTIDAD_ARTICULOS,
(SELECT ARTICULO.NOMBRE FROM ARTICULO WHERE ARTICULO.id = IT.idARTICULO) AS NOMBRE_ARTICULO
		FROM FACTURA AS FACT 
			INNER JOIN ITEM AS IT
			ON FACT.id = idFACTURA
		GROUP BY IT.idARTICULO
		ORDER BY IT.idARTICULO DESC
GO
/*Selecciona nombre, Cuenta los articulos y los agrupa por id (Primeros 3 Articulo mas vendido EN CANTIDAD)*/
SELECT TOP 3 IT.idARTICULO, COUNT( IT.idARTICULO ) AS CANTIDAD_ARTICULOS,
(SELECT ARTICULO.NOMBRE FROM ARTICULO WHERE ARTICULO.id = IT.idARTICULO) AS NOMBRE_ARTICULO
		FROM FACTURA AS FACT 
			INNER JOIN ITEM AS IT
			ON FACT.id = idFACTURA
		GROUP BY IT.idARTICULO
		ORDER BY IT.idARTICULO DESC
GO
/*Selecciona nombre, Cuenta los articulos y los agrupa por id (Articulos MENOS VENDIDO EN CANTIDAD)*/
SELECT TOP 1 IT.idARTICULO AS ID, COUNT( IT.idARTICULO ) AS CANTIDAD_ARTICULOS,
(SELECT ARTICULO.NOMBRE FROM ARTICULO WHERE ARTICULO.id = IT.idARTICULO) AS NOMBRE_ARTICULO
		FROM FACTURA AS FACT 
			INNER JOIN ITEM AS IT
			ON FACT.id = idFACTURA
		GROUP BY IT.idARTICULO
		ORDER BY IT.idARTICULO ASC
GO
/*Selecciona nombre, Cuenta los articulos y los agrupa por id (Primeros 3 Articulos MENOS VENDIDO EN CANTIDAD)*/
SELECT TOP 3 IT.idARTICULO AS ID, COUNT( IT.idARTICULO ) AS CANTIDAD_ARTICULOS,
(SELECT ARTICULO.NOMBRE FROM ARTICULO WHERE ARTICULO.id = IT.idARTICULO) AS NOMBRE_ARTICULO
		FROM FACTURA AS FACT 
			INNER JOIN ITEM AS IT
			ON FACT.id = idFACTURA
		GROUP BY IT.idARTICULO
		ORDER BY IT.idARTICULO ASC
GO

SELECT IT.idARTICULO, IT.CANTIDAD, IT.COSTO, ART.COSTO_COMPRA, ( IT.CANTIDAD * IT.COSTO ) AS CANTIDADXCOSTO, ( IT.CANTIDAD * ART.COSTO_COMPRA ) AS CANTIDADXCOSTO_COMPRA

		FROM FACTURA AS FACT 
			INNER JOIN ITEM AS IT
			ON FACT.id = IT.idFACTURA
			INNER JOIN ARTICULO AS ART
			ON ART.id = IT.idARTICULO
		GROUP BY IT.idARTICULO, IT.CANTIDAD, IT.COSTO, ART.COSTO_COMPRA
		ORDER BY IT.idARTICULO ASC
GO

SELECT TOP 3 idARTICULO, COUNT( idARTICULO ) TOTAL_ARTICULOS, SUM( CANTIDADXCOSTO ) AS CANTIDADXCOSTO_TOTAL, SUM( CANTIDADXCOSTO_COMPRA ) CANTIDADXCOSTO_COMPRA_TOTAL, ( SUM( CANTIDADXCOSTO ) - SUM( CANTIDADXCOSTO_COMPRA ) ) AS GANANCIA, NOMBRE FROM (
SELECT IT.idARTICULO, IT.CANTIDAD, IT.COSTO, ART.COSTO_COMPRA, ( IT.CANTIDAD * IT.COSTO ) AS CANTIDADXCOSTO, ( IT.CANTIDAD * ART.COSTO_COMPRA ) AS CANTIDADXCOSTO_COMPRA, ART.NOMBRE AS NOMBRE

		FROM FACTURA AS FACT 
			INNER JOIN ITEM AS IT
			ON FACT.id = IT.idFACTURA
			INNER JOIN ARTICULO AS ART
			ON ART.id = IT.idARTICULO
		--GROUP BY IT.idARTICULO, IT.CANTIDAD, IT.COSTO, ART.COSTO_COMPRA
		--ORDER BY IT.idARTICULO ASC
) AS X GROUP BY idARTICULO, NOMBRE ORDER BY idARTICULO DESC
GO
/*Mejores 3 productos respecto a la ganancia*/
SELECT TOP 3 idARTICULO, COUNT( idARTICULO ) TOTAL_ARTICULOS, SUM( CANTIDADXCOSTO ) AS CANTIDADXCOSTO_TOTAL, SUM( CANTIDADXCOSTO_COMPRA ) CANTIDADXCOSTO_COMPRA_TOTAL, ( SUM( CANTIDADXCOSTO ) - SUM( CANTIDADXCOSTO_COMPRA ) ) AS GANANCIA, NOMBRE FROM (
SELECT IT.idARTICULO, IT.CANTIDAD, IT.COSTO, ART.COSTO_COMPRA, ( IT.CANTIDAD * IT.COSTO ) AS CANTIDADXCOSTO, ( IT.CANTIDAD * ART.COSTO_COMPRA ) AS CANTIDADXCOSTO_COMPRA, ART.NOMBRE AS NOMBRE

		FROM FACTURA AS FACT 
			INNER JOIN ITEM AS IT
			ON FACT.id = IT.idFACTURA
			INNER JOIN ARTICULO AS ART
			ON ART.id = IT.idARTICULO
		--GROUP BY IT.idARTICULO, IT.CANTIDAD, IT.COSTO, ART.COSTO_COMPRA
		--ORDER BY IT.idARTICULO ASC
) AS X GROUP BY idARTICULO, NOMBRE ORDER BY GANANCIA DESC
GO

 
 