USE Liverpool
GO

SELECT * FROM ARTICULO
GO

SELECT * FROM ITEM
GO
SELECT * FROM ITEM where item.idARTICULO = '1021151331'
GO

SELECT * FROM FACTURA
GO
SELECT id, FECHA, EMPLEADO, ESTADO FROM FACTURA
GO

SELECT * FROM EMPLEADO
GO
SELECT * FROM ENTREGA
GO
SELECT id, idFactura, idEMPLEADO, FECHA FROM ENTREGA
GO

SELECT sum(IT.CANTIDAD * IT.COSTO) AS COSTO FROM ITEM AS IT
	INNER JOIN ARTICULO AS ART
	 ON IT.idARTICULO = ART.id
	 WHERE IT.idFACTURA = '1'
GO