USE EMPRESA
GO

SELECT 
	  COUNT(*) AS TOTALES,
	  (SELECT COUNT (*) FROM EMPLEADO4 WHERE SEXO = 'F') AS FEMENINO,
	  (SELECT COUNT (*) FROM EMPLEADO4 WHERE SEXO = 'M') AS MASCULINO,
	  (SELECT COUNT (*) FROM EMPLEADO4 WHERE PUESTO = 'Vendedor') AS NO_VENDEDORES,
	  (SELECT COUNT (*) FROM EMPLEADO4 WHERE PUESTO = 'Repartidor') AS NO_REPARTIDORES
	FROM EMPLEADO4
