use Liverpool
GO

SELECT 
	FACT.id AS ID_FACTURA,
	FACT.FECHA AS FECHA,
	FACT.EMPLEADO AS EMPLEADO,
	FACT.ESTADO AS ESTADO,
	IT.id AS ID_ITEM,
	IT.CANTIDAD AS CANTIDAD,
	IT.COSTO AS COSTO,
	IT.idARTICULO AS ID_ARTICULO,
	IT.idFACTURA AS ID_FACTURA
FROM FACTURA AS FACT INNER JOIN ITEM AS IT
ON FACT.id = IT.idFACTURA WHERE FACT.id = 1
GO

CREATE TABLE EMPLEADO(
	id INT PRIMARY KEY,
	APELLIDOS VARCHAR( 50 ),
	NOMBRE VARCHAR( 50 ),
	SEXO VARCHAR( 50 ),
	PUESTO VARCHAR( 50 ),
	IMAGEN VARBINARY(MAX)
)
GO
INSERT INTO EMPLEADO SELECT * FROM EMPRESA.DBO.EMPLEADO4
GO
SELECT * FROM EMPLEADO WHERE id = 201527112
GO

SELECT 
	IT.idFACTURA,
	FACT.FECHA,
	FACT.EMPLEADO,
	EMP.NOMBRE,
	EMP.APELLIDOS,
	EMP.IMAGEN,
	FACT.ESTADO,
	IT.id,
	IT.idARTICULO,
	IT.COSTO,
	IT.CANTIDAD,
	(IT.COSTO * IT.CANTIDAD) AS SUBTOTAL,
	( (IT.COSTO * IT.CANTIDAD) * 0.16) AS IVA,
	( (IT.COSTO * IT.CANTIDAD) + ( (IT.COSTO * IT.CANTIDAD) * 0.16) ) AS TOTAL,
	SUM( (IT.COSTO * IT.CANTIDAD) + ( (IT.COSTO * IT.CANTIDAD) * 0.16) ) OVER() AS GRANTOTAL,
	ART.NOMBRE
FROM FACTURA AS FACT
	INNER JOIN ITEM AS IT
	ON FACT.id = IT.idFACTURA
	INNER JOIN ARTICULO AS ART
	ON IT.idARTICULO = ART.id
	INNER JOIN EMPLEADO AS EMP
	ON FACT.EMPLEADO = EMP.id
WHERE FACT.id = 1
GROUP BY FACT.id, 
	IT.idFACTURA, 
	FACT.FECHA, 
	FACT.EMPLEADO, 
	EMP.NOMBRE,
	EMP.APELLIDOS,
	EMP.IMAGEN,
	FACT.ESTADO,
	IT.id,
	IT.idARTICULO,
	IT.COSTO,
	IT.CANTIDAD,
	ART.NOMBRE
GO

SELECT *, COUNT( * ) OVER() AS TOTAL FROM EMPLEADO
GO
SELECT *, COUNT( * ) OVER() AS TOTAL FROM EMPLEADO WHERE SEXO = 'M'
GO
SELECT *, COUNT( * ) OVER() AS TOTAL FROM EMPLEADO WHERE PUESTO = 'Repartidor'
GO