/*USE master
IF EXISTS(select * from sys.databases where name='EMPRESA')
DROP DATABASE EMPRESA
CREATE DATABASE EMPRESA;
GO*/
USE master
DROP DATABASE IF EXISTS EMPRESA;
GO
CREATE DATABASE EMPRESA;
GO

USE EMPRESA
GO

DROP TABLE IF EXISTS EMPLEADO;
GO
CREATE TABLE EMPLEADO(
	id INT PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR (50),
	GENERO VARCHAR (50),
	FECHA DATE
);
GO
--INSERTANDO DATOS
INSERT INTO EMPLEADO(
			EMPLEADO.id, 
			EMPLEADO.NOMBRE, 
			EMPLEADO.GENERO, 
			EMPLEADO.FECHA
	)
	VALUES(1, 'Jolly', 'Female', '12-06-1989'),
		  (2, 'Jon', 'Male','02-02-1974'),
		  (3, 'Sara', 'Female', '07-03-1988'),
		  (4, 'Laura', 'Female', '22-12-1981'),
		  (5, 'Alan', 'Male', '29-07-1993'),
		  (6, 'Kate', 'Female', '03-01-1985'),
		  (7, 'Joseph', 'Male', '09-04-1982'),
		  (8, 'Mice', 'Male', '16-08-1974'),
		  (9, 'Wise', 'Male', '11-11-1987'),
		  (10, 'Elis', 'Female', '28-10-1990');
	GO
SELECT * FROM EMPLEADO ORDER BY EMPLEADO.GENERO /*Orden por genero*/
GO

SELECT COUNT(*) FROM EMPLEADO /*Cuenta empleados*/
GO
SELECT COUNT(*) AS 'TOTAL MUJERES' FROM EMPLEADO WHERE EMPLEADO.GENERO = 'Female'
GO
SELECT COUNT(*) AS 'TOTAL HOMBRES' FROM EMPLEADO WHERE EMPLEADO.GENERO = 'Male'
GO

SELECT EMPLEADO.GENERO, COUNT(GENERO) AS TOTAL FROM EMPLEADO GROUP BY EMPLEADO.GENERO /*Clasificación cuenta por genero*/
GO

SELECT EMPLEADO.NOMBRE, MONTH(EMPLEADO.FECHA) AS MES_NACIMIENTO FROM EMPLEADO ORDER BY MES_NACIMIENTO/*Empleados ordenados  por fecha de nacimiento*/
GO
SELECT EMPLEADO.NOMBRE, YEAR(EMPLEADO.FECHA) AS ANIO FROM EMPLEADO ORDER BY ANIO /*Empleados ordenados por año de nacimiento*/
GO
SELECT EMPLEADO.NOMBRE, DAY(EMPLEADO.FECHA) AS DIA_NACIMIENTO FROM EMPLEADO ORDER BY DIA_NACIMIENTO /*Empleado ordenado por dia de nacimiento*/
GO

/*Empleado mas viejo*/
/*SELECT EMPLEADO.NOMBRE, MAX(YEAR(EMPLEADO.FECHA)) AS NACIMIENTO FROM EMPLEADO GROUP BY EMPLEADO.NOMBRE ORDER BY NACIMIENTO DESC offset 9 row
GO*/

/*UTILIZACIÓN DE TOP*/
SELECT TOP 1 EMPLEADO.NOMBRE, YEAR(FECHA) AS ANIO_NACIMIENTO FROM EMPLEADO ORDER BY ANIO_NACIMIENTO ASC
GO
SELECT TOP 1 WITH TIES EMPLEADO.NOMBRE, YEAR(EMPLEADO.FECHA) AS ANIO_NACIMIENTO FROM EMPLEADO ORDER BY ANIO_NACIMIENTO /*Forma correcta*/
GO
/*Utilización de MIN Y MAX*/
SELECT MIN(YEAR(EMPLEADO.FECHA)) AS ANIO_NACIMIENTO_MAS_VIEJO FROM EMPLEADO ORDER BY ANIO_NACIMIENTO_MAS_VIEJO
GO
SELECT MAX(YEAR(EMPLEADO.FECHA)) AS ANIO_NACIMIENTO_MAS_JOVEN FROM EMPLEADO ORDER BY ANIO_NACIMIENTO_MAS_JOVEN
GO
/*SUMA*/
SELECT SUM(YEAR(EMPLEADO.FECHA)) AS SUMA_ANIOS FROM EMPLEADO ORDER BY SUMA_ANIOS
GO
/*UPPER CASE*/
SELECT UPPER(EMPLEADO.NOMBRE) AS nombre from EMPLEADO
GO
/*Lower Case*/
SELECT LOWER(EMPLEADO.NOMBRE) AS nombre FROM EMPLEADO
GO
/*Count string*/
SELECT LEN(EMPLEADO.NOMBRE) AS TAMANIO_NOMBRE FROM EMPLEADO
GO
/**/