USE EMPRESA
GO

EXEC SP_HELP EMPLEADO
GO
DROP TABLE IF EXISTS EMPLEADO;
GO
CREATE TABLE EMPLEADO(
	id INT Primary KEY NOT NULL,
	NOMBRE VARCHAR (50),
	GENERO VARCHAR (50),
	FECHA DATE,
);
GO
INSERT INTO EMPLEADO(
			EMPLEADO.id, 
			EMPLEADO.NOMBRE, 
			EMPLEADO.GENERO, 
			EMPLEADO.FECHA
	)
	VALUES(1, 'Jolly', 'Female', '12-06-1989'),
		  (2, 'Jon', 'Male','02-02-1974'),
		  (3, 'Sara', 'Female', '07-03-1988'),
		  (4, 'Laura', 'Female', '22-12-1981'),
		  (5, 'Alan', 'Male', '29-07-1993'),
		  (6, 'Kate', 'Female', '03-01-1985'),
		  (7, 'Joseph', 'Male', '09-04-1982'),
		  (8, 'Mice', 'Male', '16-08-1974'),
		  (9, 'Wise', 'Male', '11-11-1987'),
		  (10, 'Elis', 'Female', '28-10-1990');
	GO

DROP TABLE IF EXISTS EMPLEADO2;
GO
CREATE TABLE EMPLEADO2(
	id INT Primary KEY NOT NULL,
	NOMBRE VARCHAR (50),
	GENERO VARCHAR (50),
	FECHA DATE,
);
GO

INSERT INTO EMPLEADO2 SELECT * FROM EMPLEADO;
GO
SELECT * FROM EMPLEADO2
GO

/*HASHING CON LA TABLA DE EMPLEADOS*/

SELECT HASHBYTES('MD5', 'HOLA') AS HASH;
GO
SELECT HASHBYTES('MD5','@@HOLA@@'); 
GO
SELECT HASHBYTES('MD5','@@1029384756HOLA@@'); 
GO

SELECT SUBSTRING(NOMBRE, 1, 1) AS SUBCADENA FROM EMPLEADO 
GO
SELECT HASHBYTES('MD5', SUBSTRING(NOMBRE, 2, 1)/*INICIO SEGUNDA LETRA SUBCADENA TAM 1*/ 
					  + SUBSTRING(NOMBRE, 1, 1) 
					  + CONVERT(VARCHAR(MAX), id)
		) FROM EMPLEADO;
GO
DROP TABLE IF EXISTS EMPLEADO3;
GO
CREATE TABLE EMPLEADO3(
	id INT Primary KEY NOT NULL,
	NOMBRE VARCHAR (50),
	GENERO VARCHAR (50),
	FECHA DATE,
	PASSWORD VARCHAR (100)
);
GO
INSERT INTO EMPLEADO3(
			EMPLEADO3.id, 
			EMPLEADO3.NOMBRE, 
			EMPLEADO3.GENERO, 
			EMPLEADO3.FECHA,
			EMPLEADO3.PASSWORD
	)
	VALUES(1, 'Jolly', 'Female', '12-06-1989', CONVERT(VARCHAR, HASHBYTES('MD5', '123'))),
		  (2, 'Jon', 'Male','02-02-1974', CONVERT(VARCHAR, HASHBYTES('MD5', 'HOLA')));
	GO
SELECT * FROM EMPLEADO3
GO

/*BUSCANDO LA CONTRASEÑA */
SELECT * FROM EMPLEADO3 WHERE PASSWORD = CONVERT(VARCHAR, HASHBYTES('MD5', '123'));
GO

/*MASTER FILES*/
SELECT * FROM SYS.master_files
GO